(function testyDefinicjiPolBur() {
  const bur = window.BurAsystent;
  function kontekst(forma) { return { szkolenieSemper: { tytułPoNormalizacjiBur: "Zażółć", sekcje: { grupaDocelowa: "Łódź", celSzkolenia: "Ćwiczenia" } }, wybranyTermin: { forma: forma || "online", miejsce: forma === "stacjonarna" ? "Łódź" : "online", dataStartBur: "01-01-2027", dataKoniecBur: "02-01-2027" } }; }
  test("katalog definicji BUR zawiera komplet aktualnych pól", function sprawdź() { sprawdzRownosc(bur.pobierzDefinicjePólWypełnieniaBur(kontekst()).length, 23); });
  test("katalog definicji BUR ma unikalne serializowalne identyfikatory", function sprawdź() { const pola = bur.pobierzDefinicjePólWypełnieniaBur(kontekst()); sprawdzRownosc(new Set(pola.map(function id(p) { return p.id; })).size, pola.length); sprawdzWarunek(Boolean(JSON.stringify(pola))); });
  test("katalog definicji BUR rozróżnia online i stacjonarną", function sprawdź() { const online = bur.pobierzDefinicjePólWypełnieniaBur(kontekst()); const stacjonarna = bur.pobierzDefinicjePólWypełnieniaBur(kontekst("stacjonarna")); sprawdzRownosc(online.find(function p(x) { return x.id === "minimum-uczestnikow"; }).wartośćProponowana, "2"); sprawdzRownosc(stacjonarna.find(function p(x) { return x.id === "minimum-uczestnikow"; }).wartośćProponowana, "5"); });
  test("katalog definicji BUR zawiera przełączniki i pola tabeli", function sprawdź() { const pola = bur.pobierzDefinicjePólWypełnieniaBur(kontekst()); sprawdzWarunek(pola.filter(function p(x) { return x.typPola === "przełącznik"; }).length >= 7); sprawdzWarunek(pola.filter(function p(x) { return x.typPola === "pole_tabeli"; }).length === 2); });
  test("opis celu do wypełnienia kończy się na pełnym zdaniu przed limitem 500 znaków", function sprawdź() { const dane = kontekst(); const pełneZdania = "Pierwsze zdanie " + "a".repeat(230) + ". Drugie zdanie " + "b".repeat(220) + "."; dane.szkolenieSemper.sekcje.celSzkolenia = pełneZdania + " Trzecie zdanie " + "c".repeat(200) + "."; const opis = bur.pobierzDefinicjePólWypełnieniaBur(dane).find(function znajdź(pole) { return pole.id === "opis-celu"; }); sprawdzRownosc(opis.wartośćProponowana, pełneZdania); });
})();
