(function testyBurIist() {
  const bur = window.BurAsystent;
  const profil = bur.pobierzProfilDostawcy("iist");
  function szkolenie() { return { profilId: "iist", tytułPoNormalizacjiBur: "Audyt ISO", sekcje: { grupaDocelowa: "Audytorzy", celEdukacyjnyOpis: "Celem szkolenia jest poznanie audytu.", korzysci: "Po zakończeniu szkolenia uczestnicy będą potrafili:\n- planować audyt", program: "1. Norma ISO\n2. Ćwiczenia" } }; }
  function definicje(forma) { return bur.pobierzDefinicjePólWypełnieniaBur({ profilId: "iist", szkolenieŹródłowe: szkolenie(), wybranyTermin: { forma: forma, miejsce: forma === "online" ? "Online" : "Warszawa", dataStartBur: "10-09-2027", dataKoniecBur: "11-09-2027", dataZakończeniaRekrutacjiBur: "09-09-2027", cena: forma === "online" ? "1 490 zł netto" : "1 690 zł netto", liczbaGodzin: forma === "online" ? "16 godzin" : "14 godzin" } }); }
  function poId(lista, id) { return lista.find(function znajdź(pozycja) { return pozycja.id === id; }); }

  test("podstawa wpisu IIST pochodzi z centralnego profilu", function sprawdź() { sprawdzRownosc(poId(definicje("online"), "podstawa-wpisu").wartośćProponowana, profil.podstawaWpisuBur); });
  test("data rekrutacji IIST jest dzień przed startem", function sprawdź() { sprawdzRownosc(poId(definicje("online"), "data-rekrutacji").wartośćProponowana, "09-09-2027"); });
  test("cena i liczba godzin IIST pochodzą z wybranego wariantu", function sprawdź() { sprawdzRownosc(poId(definicje("online"), "cena-netto").wartośćProponowana, "1490"); sprawdzRownosc(poId(definicje("online"), "liczba-godzin").wartośćProponowana, "16"); sprawdzRownosc(poId(definicje("stacjonarna"), "cena-netto").wartośćProponowana, "1690"); sprawdzRownosc(poId(definicje("stacjonarna"), "liczba-godzin").wartośćProponowana, "14"); });
  test("program IIST ma prawidłową kolejność", function sprawdź() { const program = poId(definicje("online"), "program").wartośćProponowana; sprawdzWarunek(program.indexOf("Po zakończeniu") < program.indexOf("Norma ISO")); sprawdzWarunek(program.indexOf("Norma ISO") < program.indexOf("Przebieg szkolenia")); });
  test("program IIST nie dubluje korzyści", function sprawdź() { const dane = szkolenie(); dane.sekcje.program = dane.sekcje.korzysci + "\n\n" + dane.sekcje.program; const program = bur.zbudujProgramDostawcy("iist", dane); sprawdzRownosc(program.split("Po zakończeniu szkolenia").length - 1, 1); });
  test("program IIST nie dubluje tekstu pod programem", function sprawdź() { const dane = szkolenie(); dane.sekcje.program += "\n\n" + profil.tekstPodProgramem; const program = bur.zbudujProgramDostawcy("iist", dane); sprawdzRownosc(program.split("Przebieg szkolenia może zostać").length - 1, 1); });
  test("usuwanie istniejących osób IIST czyści tabelę", async function sprawdź() { const dokument = document.implementation.createHTMLDocument("Osoby"); dokument.body.innerHTML = "<table id='osobyprowadzace-grid'><tbody><tr><td>Stara 1</td></tr><tr><td>Stara 2</td></tr></tbody></table>"; const wiersze = Array.from(dokument.querySelectorAll("tr")); const adapter = { pobierzWiersze: function () { return wiersze.filter(function (wiersz) { return wiersz.isConnected; }); }, usuńWiersz: function (wiersz) { wiersz.remove(); return true; }, dodajOsobę: function () { return true; }, potwierdźOsobę: function () { return true; } }; const wynik = await bur.zastąpOsobyProwadzące(dokument, [], adapter); sprawdzWarunek(wynik.ok); sprawdzRownosc(wynik.usunięto, 2); });
  test("dodawanie osób IIST tworzy dokładnie dwa rekordy", async function sprawdź() { const dokument = document.implementation.createHTMLDocument("Osoby"); dokument.body.innerHTML = "<table id='osobyprowadzace-grid'><tbody></tbody></table>"; const dodane = []; const adapter = { pobierzWiersze: function () { return []; }, dodajOsobę: function (osoba) { dodane.push(osoba); return true; }, potwierdźOsobę: function () { return true; } }; const wynik = await bur.zastąpOsobyProwadzące(dokument, [profil.osobaProwadzącaUsługę, profil.osobaProwadzącaWalidację], adapter); sprawdzWarunek(wynik.ok); sprawdzRownosc(dodane.length, 2); });
  test("awaria usuwania osób IIST zatrzymuje dodawanie", async function sprawdź() { const dokument = document.implementation.createHTMLDocument("Osoby"); dokument.body.innerHTML = "<table id='osobyprowadzace-grid'><tbody><tr><td>Stara</td></tr></tbody></table>"; let dodano = 0; const adapter = { pobierzWiersze: function () { return [{}]; }, usuńWiersz: function () { return false; }, dodajOsobę: function () { dodano += 1; return true; } }; const wynik = await bur.zastąpOsobyProwadzące(dokument, [profil.osobaProwadzącaUsługę], adapter); sprawdzWarunek(!wynik.ok); sprawdzRownosc(dodano, 0); });
  test("częściowe wypełnienie działa mimo błędu osób", async function sprawdź() { const dokument = document.implementation.createHTMLDocument("Częściowe"); dokument.body.innerHTML = "<input id='informacjepodstawowesekcja-tytuluslugi'><table id='osobyprowadzace-grid'><tbody><tr><td>Stara</td></tr></tbody></table>"; const wyniki = await Promise.all([bur.ustawPoleBurZWeryfikacją(dokument, { sekcja: "Informacje podstawowe", pole: "Tytuł", wartość: "Nowy tytuł", definicjaPola: { selektory: ["#informacjepodstawowesekcja-tytuluslugi"] } }), bur.zastąpOsobyProwadzące(dokument, [profil.osobaProwadzącaUsługę], { pobierzWiersze: function () { return [{}]; }, usuńWiersz: function () { return false; } })]); sprawdzWarunek(wyniki[0].ok); sprawdzWarunek(!wyniki[1].ok); });
  test("dane kontaktowe IIST są osobnymi polami", function sprawdź() { const lista = definicje("online"); sprawdzRownosc(poId(lista, "kontakt-imie").wartośćProponowana, "Ewa Nizioł"); sprawdzRownosc(poId(lista, "kontakt-email").wartośćProponowana, "bur@iist.pl"); sprawdzRownosc(poId(lista, "kontakt-telefon").wartośćProponowana, "(+48) 530 409 030"); });
  test("materiały online IIST są proponowane", function sprawdź() { sprawdzWarunek(poId(definicje("online"), "materialy-online").wartośćProponowana.includes("Cena zawiera")); });
  test("warunki uczestnictwa online IIST są proponowane", function sprawdź() { sprawdzWarunek(poId(definicje("online"), "warunki-online").wartośćProponowana.includes("PRE i POST TESTY")); });
  test("informacje dodatkowe online IIST zaczynają się od punktu", function sprawdź() { sprawdzWarunek(poId(definicje("online"), "dodatkowe-online").wartośćProponowana.startsWith("• wygodna forma")); });
  test("warunki techniczne online IIST są proponowane", function sprawdź() { sprawdzWarunek(poId(definicje("online"), "techniczne-online").wartośćProponowana.includes("platformy Zoom")); });
  test("kody dostępowe online IIST są proponowane", function sprawdź() { sprawdzWarunek(poId(definicje("online"), "kody-online").wartośćProponowana.includes("7 dni")); });
  test("teksty stacjonarne IIST są proponowane", function sprawdź() { const pole = poId(definicje("stacjonarna"), "materialy-stacjonarna"); sprawdzWarunek(pole.wartośćProponowana.includes("serwisy kawowe")); });
  test("harmonogram IIST używa adresów IIST", function sprawdź() { const pozycje = bur.zbudujPozycjeHarmonogramu({ daty: ["10-09-2027"], czyOnline: true, emailTrenera: profil.osobaProwadzącaUsługę.email, emailWalidatora: profil.osobaProwadzącaWalidację.email }); sprawdzRownosc(pozycje[0].prowadzacy, "ekspert@iist.pl"); sprawdzRownosc(pozycje[2].prowadzacy, "koordynator@iist.pl"); });
  test("harmonogram IIST nie zawiera adresów SEMPER", function sprawdź() { const pozycje = bur.zbudujPozycjeHarmonogramu({ daty: ["10-09-2027"], czyOnline: true, emailTrenera: "ekspert@iist.pl", emailWalidatora: "koordynator@iist.pl" }); sprawdzWarunek(!JSON.stringify(pozycje).includes("szkolenia-semper.pl")); });
  test("konto SEMPER blokuje profil IIST", function sprawdź() { sprawdzWarunek(!bur.czyProfilZgodnyZKontemBur("iist", { profilId: "semper" })); });
  test("regresja SEMPER zachowuje liczby uczestników i własny profil", function sprawdź() { const lista = bur.pobierzDefinicjePólWypełnieniaBur({ profilId: "semper", szkolenieŹródłowe: { profilId: "semper", sekcje: {} }, wybranyTermin: { forma: "online" } }); sprawdzRownosc(poId(lista, "minimum-uczestnikow").wartośćProponowana, "2"); sprawdzRownosc(poId(lista, "maksimum-uczestnikow").wartośćProponowana, "15"); });
})();
