(function testyPrzygotowaniaWypelnieniaBur() {
  const bur = window.BurAsystent;
  function dane() { return { szkolenie: { tytułPoNormalizacjiBur: "Zażółć", sekcje: { grupaDocelowa: "Grupa z Łodzi" } }, termin: { dataStartBur: "01-01-2027", dataKoniecBur: "02-01-2027", forma: "online" } }; }
  function dokument(wartość) { const wynik = document.implementation.createHTMLDocument("Podgląd"); wynik.body.innerHTML = "<input id='informacjepodstawowesekcja-tytuluslugi' value='" + (wartość || "") + "'><input id='informacjepodstawowesekcja-datarozpoczeciauslugi'><input id='informacjepodstawowesekcja-datazakonczeniauslugi'><input id='informacjepodstawowesekcja-datazakonczeniarekrutacji'><div id='informacjepodstawowesekcja-grupadocelowauslugi-wysiwyg'><div class='ql-editor'></div></div><input id='informacjepodstawowesekcja-minimalnaliczbauczestnikow'><input id='informacjepodstawowesekcja-maksymalnaliczbauczestnikow'>"; return wynik; }
  test("przygotowanie podglądu nie modyfikuje DOM", function sprawdź() { const d = dane(); const doc = dokument(); bur.przygotujPropozycjeWypełnieniaBur(doc, d.szkolenie, d.termin); sprawdzRownosc(doc.querySelector("#informacjepodstawowesekcja-tytuluslugi").value, ""); });
  test("podgląd oznacza uzupełnienie pustego pola jako zaznaczone", function sprawdź() { const d = dane(); const propozycja = bur.przygotujPropozycjeWypełnieniaBur(dokument(), d.szkolenie, d.termin).find(function znajdź(pozycja) { return pozycja.id === "tytul"; }); sprawdzRownosc(propozycja.status, "uzupełnienie_pustego"); sprawdzWarunek(propozycja.domyślnieZaznaczona); });
  test("podgląd oznacza identyczną wartość bez zmiany", function sprawdź() { const d = dane(); const propozycja = bur.przygotujPropozycjeWypełnieniaBur(dokument("Zażółć"), d.szkolenie, d.termin).find(function znajdź(pozycja) { return pozycja.id === "tytul"; }); sprawdzRownosc(propozycja.status, "bez_zmiany"); });
  test("podgląd oznacza konflikt jako niezaznaczony", function sprawdź() { const d = dane(); const propozycja = bur.przygotujPropozycjeWypełnieniaBur(dokument("Inna"), d.szkolenie, d.termin).find(function znajdź(pozycja) { return pozycja.id === "tytul"; }); sprawdzRownosc(propozycja.status, "konflikt"); sprawdzWarunek(!propozycja.domyślnieZaznaczona); });
})();
