(function zarejestrujKomunikaty(globalny) {
  const przestrzen = globalny.BurAsystent || {};

  przestrzen.KOMUNIKATY = {
    PING_SKRYPTU_STRONY: "PING_SKRYPTU_STRONY",
    PONG_SKRYPTU_STRONY: "PONG_SKRYPTU_STRONY",
    POBIERZ_DANE_ZE_STRONY: "POBIERZ_DANE_ZE_STRONY",
    POBIERZ_TYTUŁ_Z_BUR: "POBIERZ_TYTUŁ_Z_BUR",
    ODPOWIEDŹ_TYTUŁ_Z_BUR: "ODPOWIEDŹ_TYTUŁ_Z_BUR",
    SZUKAJ_ŁĄCZA_SEMPER: "SZUKAJ_ŁĄCZA_SEMPER",
    ODPOWIEDŹ_SZUKAJ_ŁĄCZA_SEMPER: "ODPOWIEDŹ_SZUKAJ_ŁĄCZA_SEMPER",
    IMPORTUJ_SEMPER_Z_ŁĄCZA: "IMPORTUJ_SEMPER_Z_ŁĄCZA",
    ODPOWIEDŹ_IMPORTUJ_SEMPER_Z_ŁĄCZA: "ODPOWIEDŹ_IMPORTUJ_SEMPER_Z_ŁĄCZA",
    POBIERZ_HTML_SEMPER: "POBIERZ_HTML_SEMPER",
    BŁĄD_IMPORTU_SEMPER: "BŁĄD_IMPORTU_SEMPER",
    ZAPISZ_SZKOLENIE_SEMPER: "ZAPISZ_SZKOLENIE_SEMPER",
    ODPOWIEDZ_DANE_SEMPER: "ODPOWIEDZ_DANE_SEMPER",
    ODPOWIEDZ_STATUS_STRONY: "ODPOWIEDZ_STATUS_STRONY",
    SPRAWDŹ_PROGRAM_I_HARMONOGRAM_BUR: "SPRAWDŹ_PROGRAM_I_HARMONOGRAM_BUR",
    ODPOWIEDŹ_PROGRAM_I_HARMONOGRAM_BUR: "ODPOWIEDŹ_PROGRAM_I_HARMONOGRAM_BUR",
    UZUPEŁNIJ_PROGRAM_BUR: "UZUPEŁNIJ_PROGRAM_BUR",
    GENERUJ_HARMONOGRAM_BUR: "GENERUJ_HARMONOGRAM_BUR",
    IMPORTUJ_HARMONOGRAM_XML_BUR: "IMPORTUJ_HARMONOGRAM_XML_BUR",
    WYPEŁNIJ_HARMONOGRAM_RĘCZNIE_BUR: "WYPEŁNIJ_HARMONOGRAM_RĘCZNIE_BUR",
    BLAD_PARSERA: "BLAD_PARSERA"
  };

  globalny.BurAsystent = przestrzen;
})(globalThis);
